### ISSUE TITLE
Can I make my else {} move 1 tab less?

### ISSUE THREAD

**Issue by ciwox** [ffes/indentbyfold#5] opened 2016-10-22 06:21 UTC
It looks like this right now:

```
if ($number == 1){
     echo 'test';
     } else {
     echo 'test0';
}
```

I want it like this:

```
if ($number == 1){
     echo 'test';
} else {
     echo 'test0';
}
```

Besides that, it works great :)

**Comment by ffes** [comment] 2016-11-22 14:35
I tried to reproduce this, first observation:

In PHP it works as you describe. In JavaScript and C++ it works more as expected. When you press the first `}` the plugin unidents,

But the `} else {` on one line is a problem for N++. As you can see, no folding indicator is shown on that line. The plugin has no information to indent the line.

I have to dig in a bit deeper, but my first though it this is caused by problems with the builtin language parsers of N++.

**Comment by ffes** [comment] 2020-05-12 21:01
This is basically the same problem as #1. I recently wrote a FAQ item about it: https://indentbyfold.readthedocs.io/en/latest/faq.html#faq-if-else

I am closing this one as a dup of #1

**Closed as completed by ffes** 2020-05-12 21:01 UTC
